version: "2.1"

services:
  ss_thur0:
    build:
      context: .
      dockerfile: ./SS/Dockerfile
    ports: 
      - 80:80
    environment:
      - PASSWORD=IServerDude
      - METHOD=rc4-md5
      - TIMEOUT=1500
  ssr_server0:
    build:
      context: .
      dockerfile: ./SSR/Dockerfile
    ports: 
      - 65300:65300
    environment:
      - PASSWORD=IServerDude
      - METHOD=aes-256-cfb
      - PROTOCOL=auth_aes128_md5
      - PROTOCOLPARAM=32
      - OBFS=tls1.2_ticket_auth_compatible
      - TIMEOUT=500