version: "3.7"

services:
  ss_thur:
    build:
      context: .
      dockerfile: ./SS/Dockerfile
    restart: always
    ports: 
      - 80-90:80
    environment:
      - PASSWORD=IServerDude
      - METHOD=rc4-md5
      - TIMEOUT=500
    deploy:
      replicas: 3
  ssr_thur:
    build:
      context: .
      dockerfile: ./SSR/Dockerfile
    ports: 
      - 443-453:65300
    environment:
      - PASSWORD=IServerDude
      - METHOD=aes-256-cfb
      - PROTOCOL=auth_chain_a
      - PROTOCOLPARAM=32
      - OBFS=http_post
      - TIMEOUT=500
    deploy:
      replicas: 3