version: "2.1"

services:
  ss_thur:
    build:
      context: .
      dockerfile: ./SS/Dockerfile
    ports: 
      - 80+:80
    environment:
      - PASSWORD=IServerDude
      - METHOD=rc4-md5
      - TIMEOUT=500
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
  ssr_thur:
    build:
      context: .
      dockerfile: ./SSR/Dockerfile
    ports: 
      - 443+:65300
    environment:
      - PASSWORD=IServerDude
      - METHOD=aes-256-cfb
      - PROTOCOL=auth_chain_a
      - PROTOCOLPARAM=32
      - OBFS=http_post
      - TIMEOUT=500
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10